### ISSUE TITLE
Release model (besides demo) on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [aim-uofa/Framer#1]
Hello @qiuyu96  🤗 

I'm Niels and work as part of the open-source team at Hugging Face. I discovered your work through the daily papers: https://huggingface.co/papers/2410.18978. The paper page lets people discuss about your paper and lets them find artifacts about it (your models for instance) you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the checkpoints you've train on https://huggingface.co/models? Hosting on Hugging Face will give you more visibility/enable better discoverability. We can add tags in the model cards so that people find the models easier, link it to the paper page, etc.

If you're down, leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a PyTorch model, you can use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds from_pretrained and push_to_hub to the model which lets you to upload the model and people to download and use models right away.
If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).

After uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model.

Kind regards,

Niels

**Comment by NielsRogge** [comment]
Btw for the Gradio demo, ZeroGPU might be the best option: https://huggingface.co/zero-gpu-explorers.

Let me know if you need any help

**Comment by cshen** [comment]
thanks we are working on a huggingface demo right now

**Comment by qiuyu96** [comment]
> Hello @qiuyu96 🤗
> 
> I'm Niels and work as part of the open-source team at Hugging Face. I discovered your work through the daily papers: https://huggingface.co/papers/2410.18978. The paper page lets people discuss about your paper and lets them find artifacts about it (your models for instance) you can also claim the paper as yours which will show up on your public profile at HF.
> 
> Would you like to host the checkpoints you've train on https://huggingface.co/models? Hosting on Hugging Face will give you more visibility/enable better discoverability. We can add tags in the model cards so that people find the models easier, link it to the paper page, etc.
> 
> If you're down, leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a PyTorch model, you can use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds from_pretrained and push_to_hub to the model which lets you to upload the model and people to download and use models right away. If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).
> 
> After uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model.
> 
> Kind regards,
> 
> Niels

Hello, thank you for your interest. We are currently developing a Hugging Face demo and will release it very soon.

**Comment by encounter1997** [comment]
> Btw for the Gradio demo, ZeroGPU might be the best option: https://huggingface.co/zero-gpu-explorers.
> 
> Let me know if you need any help

Hi, Niels. Thanks for reaching out!

We are working on building the radio demo for Framer. Though the radio demo runs well with our local GPU or the T4 GPU on huggingface space, it encounters bugs when running on huggingface ZeroGPU. The error information is shown below.

![295dfc677d686863709b8d21812f6c71](https://github.com/user-attachments/assets/67202508-e236-4c1b-a46b-677b8ecc78bc)

Could you please help us fix this problem?

**Comment by NielsRogge** [comment]
Thanks for reporting, someone from the HF team will take a look

**Comment by hysts** [comment]
Hi @encounter1997 

Looks like your Space is using a private model, so I can't debug it on my end. My guess is that the issue might be related to functions returning `gr.State`. https://huggingface.co/spaces/wwen1997/Framer/blob/1d235142f450b55c0b95d94162e886c2a45dc552/app.py#L529-L568
In general, if you want to update the value of `gr.State`, you are supposed to return values like `None` or `[]`. Returning `gr.State` itself could lead to unexpected behavior.

[This Space](https://huggingface.co/spaces/TencentARC/ImageConductor) has similar functionality and is running on ZeroGPU, so you might want to take a look at its code.

**Comment by LaLaLailalai** [comment]
Hi @qiuyu96,
Thanks for the amazing work!
I'm trying to run the demo on hugging face, but after I click "Add Drag Track" it shows errors, do you know how to solve this problem?
![image](https://github.com/user-attachments/assets/5f6c4329-1ec9-49d4-9123-6a70c78b6084)

**Comment by encounter1997** [comment]
> Hi @qiuyu96, Thanks for the amazing work! I'm trying to run the demo on hugging face, but after I click "Add Drag Track" it shows errors, do you know how to solve this problem? ![image](https://private-user-images.githubusercontent.com/16380906/381408554-5f6c4329-1ec9-49d4-9123-6a70c78b6084.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDMwODMsIm5iZiI6MTczMDM0Mjc4MywicGF0aCI6Ii8xNjM4MDkwNi8zODE0MDg1NTQtNWY2YzQzMjktMWVjOS00OWQ0LTkxMjMtNmE3MGM3OGI2MDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAyNDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZGY2ZDg2MTUwNTUzNjViNjQzOGU5ODM2NWVmNDE1MGNhYTBjNTY1MTVjMWRkZTE1MDgyZGNlODgxMzAzOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.392cgnk5pGz86Usn61iW5o_09SVJrDmnWzh4KFSNjrg)


Hi, thanks for your interest! 

Now the images can only be **uploaded via the 'Upload Start Image' and 'Upload End Image' buttons on the left**, please do not upload images using the display windows on the right. We will update the gradio demo to support both ways for image uploading.
