### ISSUE TITLE
Release code and checkpoint

### ISSUE THREAD

**Issue by yongjinColinChoi** [aim-uofa/Framer#2]
Thanks for your awesome work. 

In a previous commit, it was mentioned that the inference code and training code would be released, but now the README has been updated to only include the Hugging Face app. Do you plan to release the inference code, training code, and model checkpoint? If so, when do you plan to make them available?

**Comment by encounter1997** [comment]
> Thanks for your awesome work.
> 
> In a previous commit, it was mentioned that the inference code and training code would be released, but now the README has been updated to only include the Hugging Face app. Do you plan to release the inference code, training code, and model checkpoint? If so, when do you plan to make them available?

Hi, thanks for your interest!

You can run inference using our [gradio demo](https://huggingface.co/spaces/wwen1997/Framer), with inference code available in the [file folder](https://huggingface.co/spaces/wwen1997/Framer/tree/main). 

The model checkpoint (and probably the training code) will be released, but we are still working on an internal process to make it publicly available. Please stay tuned.

**Comment by encounter1997** [comment]
> Thanks for your awesome work.
> 
> In a previous commit, it was mentioned that the inference code and training code would be released, but now the README has been updated to only include the Hugging Face app. Do you plan to release the inference code, training code, and model checkpoint? If so, when do you plan to make them available?

Hi, thanks for your interest!

Currently, you can run inference using our [gradio demo](https://huggingface.co/spaces/wwen1997/Framer), with inference code available in the [file folder](https://huggingface.co/spaces/wwen1997/Framer/tree/main). 

The model checkpoint (and probably the training code) will be released, but we are still working on an internal process to make it publicly available. Please stay tuned.

**Comment by Mikerhinos** [comment]
Any idea if we're speaking days, weeks or even months ?

**Comment by endman100** [comment]
Is there any new information?

**Comment by encounter1997** [comment]
Both code and checkpoints have been made available. Let me know if you have further questions!
