### ISSUE TITLE
run failed, click run, an error message is displayed

### ISSUE THREAD

**Issue by huanxve** [aim-uofa/Framer#3]
https://huggingface.co/spaces/wwen1997/Framer
run failed, click run, an error message is displayed

**Comment by encounter1997** [comment]
> https://huggingface.co/spaces/wwen1997/Framer run failed, click run, an error message is displayed

Hi, thanks for your interest! 

Now the images can only be **uploaded via the 'Upload Start Image' and 'Upload End Image' buttons on the left**, please do not upload images using the display windows on the right. 

We will update the gradio demo to support both ways for image uploading.

**Comment by encounter1997** [comment]
We have disabled the image uploading in the display box, running with image upload buttons on the left should work. Letting us know if you have further questions.
