### ISSUE TITLE
Different result in VIDM paper

### ISSUE THREAD

**Issue by Yolice** [aim-uofa/Framer#4]
I note that in the VIDM paper they report PSNR and SSIM for mid-frame scores, and the LPIPS has significant differences from your results. May I ask if your experiment is testing the Davis-7 dataset being cropped at 256*256 size?

**Comment by encounter1997** [comment]
Hi, thanks for your interest! 

The DAVIS-7 evaluation dataset is cropped at 256x256 resolution, using the official code [here](https://github.com/vidim-interpolation/vidim-interpolation.github.io/tree/main/static/scripts). Besides, we use the LPIPS implementation [here](https://pypi.org/project/lpips/).

**Comment by Yolice** [comment]
> Hi, thanks for your interest!
> 
> The DAVIS-7 evaluation dataset is cropped at 256x256 resolution, using the official code [here](https://github.com/vidim-interpolation/vidim-interpolation.github.io/tree/main/static/scripts). Besides, we use the LPIPS implementation [here](https://pypi.org/project/lpips/).

hi,thanks for your reply.
Can I ask which network you used, VGG or Alexnet, and what packages the SSIM and PSNR metrics were calculated from (e.g. Skimage?).

**Comment by encounter1997** [comment]
Certainly, we use VGG for LPIPS calculation. We follow the PSNR and SSIM implementation in AMT repo [here](https://github.com/MCG-NKU/AMT/blob/main/metrics/psnr_ssim.py).

**Comment by Yolice** [comment]
> Certainly, we use VGG for LPIPS calculation. We follow the PSNR and SSIM implementation in AMT repo [here](https://github.com/MCG-NKU/AMT/blob/main/metrics/psnr_ssim.py).

Thanks for your reply, May I ask again if the FID and FVD calculation scripts are available.
Thank you very much

**Comment by encounter1997** [comment]
We use [pytorch-fid](https://github.com/mseitzer/pytorch-fid) for FID calculation and followed [TATS](https://github.com/songweige/TATS/tree/main/tats/fvd) for FVD calculation.
