### ISSUE TITLE
Could you share some information about how many training data you used,  and the cost of training，thanks.

### ISSUE THREAD

**Issue by pekinghk** [aim-uofa/Framer#6]

**Comment by encounter1997** [comment]
https://huggingface.co/datasets/nkp37/OpenVid-1M/tree/main

**Comment by encounter1997** [comment]
Hi, thanks for your interest!

The model is trained on the HD subset of the [OpenVid](https://huggingface.co/datasets/nkp37/OpenVid-1M) dataset, which contains 0.4M high-quality videos. The training is performed on 16 NVIDIA A100 GPUs, with a total batch size of 16. Framer is trained in two stages. Specifically, the UNet is first trained for 100k iterations, then the controlling branch is trained for 10k iterations.

**Comment by pekinghk** [comment]
> Hi, thanks for your interest!
> 
> The model is trained on the HD subset of the [OpenVid](https://huggingface.co/datasets/nkp37/OpenVid-1M) dataset, which contains 0.4M high-quality videos. The training is performed on 16 NVIDIA A100 GPUs, with a total batch size of 16. Framer is trained in two stages. Specifically, the UNet is first trained for 100k iterations, then the controlling branch is trained for 10k iterations.

Thanks for your reply. How great jop your team did!
