### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Rubenacp** [aim-uofa/Framer#8]
Hi, the demo doesn't work. It allows me to upload the images, but when I mark a path the images disappear and it shows an error.
![Captura de pantalla 2024-11-12 113135](https://github.com/user-attachments/assets/8cd72cb1-b101-4136-8a9b-006bc4c3d8b8)

**Comment by encounter1997** [comment]
Hi, thanks for your interest. 
We did not meet a similar problem. Could you please provide more details for reproducing the problem?

**Comment by encounter1997** [comment]
BTW, you should click "Add Drag Trajectory" before drawing paths on the images. 

The detailed instructions are shown on the top of the interface.

![image](https://github.com/user-attachments/assets/ad7dd7db-6ff3-4d38-baf4-df4a6a6641d2)
