### ISSUE TITLE
authenticated

### ISSUE THREAD

**Issue by zcdliuwei** [aim-uofa/Framer#9]
When I use your code（https://huggingface.co/spaces/wwen1997/Framer/tree/main）, install the necessary dependencies, and run app.py to execute the model download section, I receive the following error message. It seems that I do not have permission to ask your pre trained model：
![image](https://github.com/user-attachments/assets/f60aec5b-9a3f-40db-90a5-5201af3a2c5b)

How to solve this problem,
Looking forward to your reply

**Comment by encounter1997** [comment]
Hi, thanks for your interest. The model weight was private. Now, we have made it public [here](https://huggingface.co/wwen1997/framer_512x320). Please retry the running command.

**Comment by zcdliuwei** [comment]
> Hi, thanks for your interest. The model weight was private. Now, we have made it public [here](https://huggingface.co/wwen1997/framer_512x320). Please retry the running command.

thanks!
